homepage:
    path:     /
    defaults: { _controller: TodoBundle:Todo:index }

list_all:
    path:     /listall
    defaults: { _controller: TodoBundle:Todo:listAll }

show:
    path:     /show/{id}
    defaults: { _controller: TodoBundle:Todo:show }
    requirements:
            id: '\d+'

create:
    path:     /create
    defaults: { _controller: TodoBundle:Todo:create }

edit:
    path:     /edit/{id}
    defaults: { _controller: TodoBundle:Todo:edit }
    requirements:
            id: '\d+'

delete:
    path:     /delete/{id}
    defaults: { _controller: TodoBundle:Todo:delete }
    requirements:
            id: '\d+'
